using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Data.SqlClient;
using System.Windows.Forms;

namespace CCITLibrary
{
    class AutoGeneratedID
    {
        public string AutoIDMember()
        {
            String id = null;
            Koneksi conn = new Koneksi();
            SqlConnection koneksi = conn.con();


            try
            {
                using (koneksi)
                {
                    koneksi.Open();
                    string sql = "select top 1 id_member from tb_Member order by id_member desc";
                    SqlCommand sqlcom = new SqlCommand(sql, koneksi);

                    using (sqlcom)
                    {
                        SqlDataReader dr = sqlcom.ExecuteReader();
                        if (dr.Read())
                        {
                            string id_member = dr.GetString(0);
                            int subid = Convert.ToInt32(id_member.Substring(1));

                            if (subid < 9)
                            {
                                id = "M000" + (subid + 1).ToString();
                            }

                            else if (subid < 100)
                            {
                                id = "M00" + (subid + 1).ToString();
                            }

                            else if (subid < 1000)
                            {
                                id = "M0" + (subid + 1).ToString();
                            }

                            else if (subid < 10000)
                            {
                                id = "M" + (subid + 1).ToString();
                            }
                        }
                        else
                        {
                            id = "M0001";
                        }
                    }
                    koneksi.Close();
                }
            }
            catch (Exception e)
            {
                MessageBox.Show(e.Message);
            }
            return id;
        }

        public string AutoIDAdmin()
        {
            String id = null;
            Koneksi conn = new Koneksi();
            SqlConnection koneksi = conn.con();


            try
            {
                using (koneksi)
                {
                    koneksi.Open();
                    string sql = "select top 1 id_admin from tb_Admin order by id_admin desc";
                    SqlCommand sqlcom = new SqlCommand(sql, koneksi);

                    using (sqlcom)
                    {
                        SqlDataReader dr = sqlcom.ExecuteReader();
                        if (dr.Read())
                        {
                            string id_admin = dr.GetString(0);
                            int subid = Convert.ToInt32(id_admin.Substring(1));

                            if (subid < 9)
                            {
                                id = "A000" + (subid + 1).ToString();
                            }

                            else if (subid < 100)
                            {
                                id = "A00" + (subid + 1).ToString();
                            }

                            else if (subid < 1000)
                            {
                                id = "A0" + (subid + 1).ToString();
                            }

                            else if (subid < 10000)
                            {
                                id = "A" + (subid + 1).ToString();
                            }
                        }
                        else
                        {
                            id = "A0001";
                        }
                    }
                    koneksi.Close();
                }
            }
            catch (Exception e)
            {
                MessageBox.Show(e.Message);
            }
            return id;
        }

        public string AutoIDBuku()
        {
            String id = null;
            Koneksi conn = new Koneksi();
            SqlConnection koneksi = conn.con();


            try
            {
                using (koneksi)
                {
                    koneksi.Open();
                    string sql = "select top 1 id_buku from tb_Buku order by id_buku desc";
                    SqlCommand sqlcom = new SqlCommand(sql, koneksi);

                    using (sqlcom)
                    {
                        SqlDataReader dr = sqlcom.ExecuteReader();
                        if (dr.Read())
                        {
                            string id_buku = dr.GetString(0);
                            int subid = Convert.ToInt32(id_buku.Substring(1));

                            if (subid < 9)
                            {
                                id = "B000" + (subid + 1).ToString();
                            }

                            else if (subid < 100)
                            {
                                id = "B00" + (subid + 1).ToString();
                            }

                            else if (subid < 1000)
                            {
                                id = "B0" + (subid + 1).ToString();
                            }

                            else if (subid < 10000)
                            {
                                id = "B" + (subid + 1).ToString();
                            }
                        }
                        else
                        {
                            id = "B0001";
                        }
                    }
                    koneksi.Close();
                }
            }
            catch (Exception e)
            {
                MessageBox.Show(e.Message);
            }
            return id;
        }

        public string AutoIDKategoriBuku()
        {
            String id = null;
            Koneksi conn = new Koneksi();
            SqlConnection koneksi = conn.con();


            try
            {
                using (koneksi)
                {
                    koneksi.Open();
                    string sql = "select top 1 id_kategori from tb_Kategori order by id_kategori desc";
                    SqlCommand sqlcom = new SqlCommand(sql, koneksi);

                    using (sqlcom)
                    {
                        SqlDataReader dr = sqlcom.ExecuteReader();
                        if (dr.Read())
                        {
                            string id_kategori = dr.GetString(0);
                            int subid = Convert.ToInt32(id_kategori.Substring(1));

                            if (subid < 9)
                            {
                                id = "K0" + (subid + 1).ToString();
                            }
                            else if (subid < 100)
                            {
                                id = "K" + (subid + 1).ToString();
                            }
                          }
                        else
                        {
                            id = "K01";
                        }
                    }
                    koneksi.Close();
                }
            }
            catch (Exception e)
            {
                MessageBox.Show(e.Message);
            }
            return id;
        }

        public string AutoIDRakBuku()
        {
            String id = null;
            Koneksi conn = new Koneksi();
            SqlConnection koneksi = conn.con();


            try
            {
                using (koneksi)
                {
                    koneksi.Open();
                    string sql = "select top 1 id_rak from tb_Rak order by id_rak desc";
                    SqlCommand sqlcom = new SqlCommand(sql, koneksi);

                    using (sqlcom)
                    {
                        SqlDataReader dr = sqlcom.ExecuteReader();
                        if (dr.Read())
                        {
                            string id_rak = dr.GetString(0);
                            int subid = Convert.ToInt32(id_rak.Substring(1));

                            if (subid < 9)
                            {
                                id = "R0" + (subid + 1).ToString();
                            }
                            else if (subid < 100)
                            {
                                id = "R" + (subid + 1).ToString();
                            }
                        }
                        else
                        {
                            id = "R01";
                        }
                    }
                    koneksi.Close();
                }
            }
            catch (Exception e)
            {
                MessageBox.Show(e.Message);
            }
            return id;
        }

        public string AutoIDPeminjaman()
        {
            String id = null;
            Koneksi conn = new Koneksi();
            SqlConnection koneksi = conn.con();


            try
            {
                using (koneksi)
                {
                    koneksi.Open();
                    string sql = "select top 1 id_peminjaman_detail from tb_Peminjaman_Details order by id_peminjaman_detail desc";
                    SqlCommand sqlcom = new SqlCommand(sql, koneksi);

                    using (sqlcom)
                    {
                        SqlDataReader dr = sqlcom.ExecuteReader();
                        if (dr.Read())
                        {
                            string id_peminjaman = dr.GetString(0);
                            int subid = Convert.ToInt32(id_peminjaman.Substring(1));

                            if (subid < 9)
                            {
                                id = "P000" + (subid + 1).ToString();
                            }

                            else if (subid < 100)
                            {
                                id = "P00" + (subid + 1).ToString();
                            }

                            else if (subid < 1000)
                            {
                                id = "P0" + (subid + 1).ToString();
                            }

                            else if (subid < 10000)
                            {
                                id = "P" + (subid + 1).ToString();
                            }
                        }
                        else
                        {
                            id = "P0001";
                        }
                    }
                    koneksi.Close();
                }
            }
            catch (Exception e)
            {
                MessageBox.Show(e.Message);
            }
            return id;
        }

    }
}
